### ISSUE TITLE
ExpDate and Expdate cause issues with VB.NET

### ISSUE THREAD

**Issue by GtlBear** [Moneris/eCommerce-Unified-API-dotNet#4]
There is an issue with this library.

A couple of methods (ResCardToken for example) has two properties - ExpDate and Expdate.

While this is OK with C# as it is case sensitive, this is not the case for VB.NET and results in and ambiguity error.

Please address ASAP.

Thanks

**Comment by MonerisSolutions** [comment]
Thanks for your response. We are working on fixing this issue and the new APIs are currently being tested for QA. Once that is complete we will update GitHub with the new files.
